-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 00:10:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pv2` DEFAULT CHARACTER SET utf8 ;
USE `pv2` ;

-- -----------------------------------------------------
-- Table `pv2`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pv2`.`clientes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `edad` INT(3) UNSIGNED NOT NULL,
  `nacimiento` DATETIME NOT NULL,
  `antiguedad` INT(3) UNSIGNED NOT NULL,
  `descuento` FLOAT UNSIGNED NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `celular` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1033
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pv2`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pv2`.`documento` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(10) UNSIGNED NOT NULL,
  `fecha_venta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descuento` FLOAT UNSIGNED NOT NULL,
  `iva` FLOAT UNSIGNED NOT NULL,
  `monto` FLOAT UNSIGNED NOT NULL,
  `id_documento` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_documento` (`id_documento` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `documento_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pv2`.`clientes` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pv2`.`documento_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pv2`.`documento_detalle` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_documento` VARCHAR(255) NOT NULL,
  `id_producto` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `importe` FLOAT UNSIGNED NOT NULL,
  `cantidad` INT(10) UNSIGNED NOT NULL,
  `monto` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_documento_idx` (`id_documento` ASC) VISIBLE,
  CONSTRAINT `documento_detalle_ibfk_1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `pv2`.`documento` (`id_documento`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pv2`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pv2`.`productos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `importe` FLOAT UNSIGNED NOT NULL,
  `stock` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1031
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
